### ISSUE TITLE
发现了个关于NAT机的问题

### ISSUE THREAD

**Issue by miaowmint** [nodecook/feedback#2]
似乎节点是以IP为单位的
我放了一些共享IPV4的nat机作为节点；然后我发现，如果有另一个人的机器和我的nat是同一个IP，并且也搭了这个Agent的话（端口肯定是不同的），那这个节点就会一会出现在我的节点列表里，一会又消失了，应该是出现在别人的节点列表里了；并且当节点出现在我的节点列表里的时候，我就能修改该节点对应的广告，那同理，我们两个都能修改这个IP对应的广告，不过由于我是后来的，我就没修改人家的广告。
但是这就有个问题了，是同一个IP算一个节点，还是同IP不同端口也算不同节点，怎么判定节点归属，并且这个广告的编辑权交给谁，是先来后到，还是交给拥有母鸡的服务商，还是干脆任由随意更改

**Comment by nodecook-dev** [comment]
确实是有这个问题，服务器是按照IP来识别节点的，之前这部分处理逻辑不太完善，我感觉对于这种机器，就谁先添加属于谁？然后如果先添加的离线了就将所有权给后面的？

**Comment by miaowmint** [comment]
> 确实是有这个问题，服务器是按照IP来识别节点的，之前这部分处理逻辑不太完善，我感觉对于这种机器，就谁先添加属于谁？然后如果先添加的离线了就将所有权给后面的？

那也不太好搞，毕竟我发现总是有节点莫名其妙的掉线，比如说我这台机器一直在挂着agent，但是意外掉线了，所以我觉得最好是优化下节点逻辑

**Comment by miaowmint** [comment]
另外我在论坛上看到老哥你说 _下一版本的agent不再要求需要公网IP_ ，我挺好奇的这是怎么做到的，还有到时候又该怎么判定节点呢

**Comment by nodecook-dev** [comment]
现在多个NAT机器相同IP不会冲突了，但是一次只会显示一个
