### ISSUE TITLE
Arc 浏览器访问页面时无法正确适应窗口大小

### ISSUE THREAD

**Issue by s-leeq** [nodecook/feedback#6]
如题，即使将左侧边栏拉到最窄，页面也无法调整到正确比例，如下图右侧所示：

<img width="1320" alt="Xnip2024-04-12_21-09-44" src="https://github.com/nodecook/feedback/assets/43868433/1e01f8b5-d5d1-4398-9f15-2d4f16681ecf">

**Comment by nodecook-dev** [comment]
奇怪，我这没有复现，是屏幕太小了吗

**Comment by s-leeq** [comment]
> 奇怪，我这没有复现，是屏幕太小了吗

有可能，我这边是13寸的屏幕，估计是有点小了🤔

**Comment by s-leeq** [comment]
问题已解决，感谢:D
